version: '3'

services:
  hackathonpostgres:
    container_name: hackathonpostgres
    image: postgres:11.0
    ports:
      - "5434:5432"
    environment:
        POSTGRES_USER: teste
        POSTGRES_PASSWORD: teste
        POSTGRES_DB: teste
    networks:
      - hackaton_network
  hackathonapi:
    container_name: hackathonapi
    restart: unless-stopped
    build: .
    ports:
      - 3050:3050
      - 9229:9229
    volumes:
      - .:/app/
      - /app/node_modules/
    command: npm run start
    # command: node --inspect=0.0.0.0 server.js
    networks:
      - hackaton_network
    depends_on: 
      - hackathonpostgres

networks:
  hackaton_network:
    driver: bridge

